### ISSUE TITLE
div bounce 

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#1]
Hi @thomasjbradley, 

Am trying to make my bunny div bounce (make the parent bounce up and down, so that the children elements move with it, but still retain their individual animations).

For some reason it's not working?

This is my CSS

```
.bunny {
    position: relative;
    width: 150px;
    height: 10px;
    margin: 0 0 25% 10%;
    background-color: rgba(255, 0, 0, 0.5);
}

@-webkit-keyframes bounce {
    0% {
        transform: translate(0);
    }

     100% {
        transform: translate(100px, 100px);
    }
}

.bunny:hover .bunny{
    -webkit-animation: bounce 1s ease-in-out alternate infinite;
    animation: bounce 1s ease-in-out alternate infinite;
}

```

**Comment by thomasjbradley** [comment]
On this line here: 

``` css
.bunny:hover .bunny {
```

There's an extra `.bunny`—`.bunny` isn’t inside `.bunny`.

**Comment by vivkay** [comment]
Do I need to create another div to wrap around it then? And then style it like this:

(it's still not working @thomasjbradley)

```
.parent:hover bunny {
    -webkit-animation: bounce 1s ease-in-out alternate infinite;
    animation: bounce 1s ease-in-out alternate infinite;
}
```

**Comment by vivkay** [comment]
(When I just do this, it doesn't change either):

```
.bunny:hover {
    -webkit-animation: bounce 1s ease-in-out alternate infinite;
    animation: bounce 1s ease-in-out alternate infinite;
}
```

**Comment by vivkay** [comment]
Also @thomasjbradley ...if I can control the parent (and keep the animations of the children inside active), can I have this animated bunny hop off the screen?

So it would start at the left side of the page, and then bounce off towards the right? So that when the user clicks the bunny 'let's go!' he animates and bounces off screen. It would be a one time animation.

Thanks!

**Comment by vivkay** [comment]
Ok last question on a similar topic: could I have a different animation state for hover and for click?

So hovering: he twitches
Click: he bounces off the page 

?

Thanks!

**Comment by vivkay** [comment]
(the parent bouncing up and down totally works...I was previewing it from the live site, OOPSIES!)

**Comment by vivkay** [comment]
But I still can't make him bounce off the screen (even with the 100% value for the translateX coordinate at 1000px):

```
.parent:hover {
    -webkit-animation: move 1s ease-in-out alternate;
    animation: move 1s ease-in-out alternate;
}

@-webkit-keyframes move {
    0% {
        transform: translate(0);
    }

     50% {
        transform: translateX(100px);
    }
}

```

**Comment by thomasjbradley** [comment]
In this scenario translate doesn’t really make sense. Translate is based on the current location of the bunny. You’d really need to use `top` and `left` so the coordinates can be based on the parent element/screen.
