### ISSUE TITLE
question: alt tags

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#10]
@thomasjbradley For the alt tags, should we put descriptions on non-essential elements (for example, my floating bunny rabbit?) In my website the text is the core content, and the images are supporting. Can I then leave their alt tags as such: alt="" ?

**Comment by thomasjbradley** [comment]
Yes, that's what you do. But make sure to test with VoiceOver and see that it makes sense.

**Comment by vivkay** [comment]
Will do captain! :ocean:
