### ISSUE TITLE
fat bunny

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#11]
@thomasjbradley

(This is like being in class–but virtually. Oooo!)

Anyway, for smushing I have only a handful of images on my site and most are super small. My only concern is about my main bunny, which has some effects on it (texture, gradient). It's 456KB but has been smushed with image optim (PNG). Is he ok to stay?

![screen shot 2015-04-13 at 6 26 52 pm](https://cloud.githubusercontent.com/assets/6340292/7126864/07e5774a-e20b-11e4-875e-f9f0f0e0e64f.png)

**Comment by thomasjbradley** [comment]
That's kinda big, but I don't know if it can be made any smaller.

**Comment by thomasjbradley** [comment]
So... probably okay.

**Comment by vivkay** [comment]
Ok. All my other images are like 3kb...(he's the only fat one in there)
