### ISSUE TITLE
exclaim!

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#12]
Haha! I just listened to the whole site with voiceover (in an Aussie accent). It's awesome, except at the end it reads out the exclamation mark, which is weird. Or is it?
:8ball: 

@thomasjbradley

**Comment by thomasjbradley** [comment]
I dunno... you tell me if that's weird. Where does it happen in the website?

**Comment by vivkay** [comment]
It's at the very end. It just reads "the sky's the limit for your website design, exclaim" (the sky's the limit for your website design!)

**Comment by vivkay** [comment]
hmm...I'll take it off. I think it's weird. Is there a way of tricking the accessibility reader not to read it out loud, or do I have to just replace it with a full-stop/period?

**Comment by thomasjbradley** [comment]
Okay; sounds good.

**Comment by vivkay** [comment]
okie :last_quarter_moon_with_face:
