### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#13]
The CSS validator is saying there is a parse error on the lines that I have the 'calc' here:

![screen shot 2015-04-13 at 7 02 25 pm](https://cloud.githubusercontent.com/assets/6340292/7127273/befcb5de-e20f-11e4-8114-1a7e06c8e191.png)

What does that mean @thomasjbradley?

**Comment by vivkay** [comment]
OOHHHH the spacing around the –

Got it!

**Comment by vivkay** [comment]
Eep! but now my bunny's moved too far. When I try to change it's position (left) it won't move, and it's crossed out in the inspector. Any ideas @thomasjbradley?

**Comment by vivkay** [comment]
![screen shot 2015-04-13 at 7 07 36 pm](https://cloud.githubusercontent.com/assets/6340292/7127312/63b3dfc6-e210-11e4-9926-5f24cdb5bc11.png)

**Comment by vivkay** [comment]
uh oh - the internet tells me the spacing was correct around the math operator...

**Comment by vivkay** [comment]
So I'm back to the fist issue/the parse error!

**Comment by vivkay** [comment]
![screen shot 2015-04-13 at 7 12 04 pm](https://cloud.githubusercontent.com/assets/6340292/7127361/04bf3e2e-e211-11e4-9088-d68b95e954a7.png)

A person in a forum said that the parse error is a validator bug. Is this something I can then ignore @thomasjbradley?

**Comment by vivkay** [comment]
:palm_tree:

**Comment by thomasjbradley** [comment]
Totally ignorable.

**Comment by vivkay** [comment]
sweeeeet :tangerine:
