### ISSUE TITLE
javascript validator!

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#14]
@thomasjbradley

For my javascript validating, I used JSLint and JSHint and I'm not sure how to appease their anger!

First, they are saying I have undefined variables all over the place. 

And then, I'm missing 'use strict' statements, and have things appearing on unexpected lines.

Heeelp!

**Comment by vivkay** [comment]
![screen shot 2015-04-13 at 7 38 14 pm](https://cloud.githubusercontent.com/assets/6340292/7127636/e33d6b78-e214-11e4-991b-a0d21ae98f9c.png)
![screen shot 2015-04-13 at 7 37 55 pm](https://cloud.githubusercontent.com/assets/6340292/7127638/e5b70a4e-e214-11e4-8e37-46c5c60faa0b.png)

**Comment by thomasjbradley** [comment]
Don't use JSLint—it's purpose is to hurt your feelings.

JSHint is good, but go to configure and specify that you're using jQuery and in browser.

**Comment by vivkay** [comment]
LOL

**Comment by vivkay** [comment]
phewwww that configure tab solved all. It's happy now that it's got jQuery on the list. Woohoo! :cake:
