### ISSUE TITLE
WAI-ARIA landmark roles

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#15]
erm... what are "WAI-ARIA landmark roles" and how do I know if I have them? @thomasjbradley 

Google tried to help, but just confused me more.

**Comment by thomasjbradley** [comment]
You really should have come to class today; we reviewed all the requirements together. :wink:

https://github.com/algonquindesign/html-css/tree/gh-pages/accessibility#wai-aria-roles

**Comment by vivkay** [comment]
Sorry Thomas! I thought it was just a working period so I opted to work from home :( I'll be there next week! :pineapple:
