### ISSUE TITLE
timing problemo

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#16]
My 'add some style' bunny animation (with the stars and hat appearance) work perfectly on Chrome and Firefox. @thomasjbradley

BUT Safari on my computer and my iPad have the same problem: the timing is way off. The stars appear, and then there's nothing for a second, and then the hat suddenly appears. 

Any ideas?

:rabbit:

**Comment by thomasjbradley** [comment]
Huh. All I can think of is a performance issue.

Try adding `transform: translateZ(0)` to the parent `<div>`.

**Comment by vivkay** [comment]
Hmm that didn't seem to work. Any other ideas?

**Comment by vivkay** [comment]
![screen shot 2015-04-14 at 9 31 31 am](https://cloud.githubusercontent.com/assets/6340292/7137646/207f2da4-e289-11e4-8370-939f20de4721.png)

CSS
![screen shot 2015-04-14 at 9 31 19 am](https://cloud.githubusercontent.com/assets/6340292/7137653/2c464974-e289-11e4-8eba-eeb08c44059f.png)

**Comment by vivkay** [comment]
(oops,  just corrected the missing semicolon in the css, but no change still)

**Comment by thomasjbradley** [comment]
Double check the percentages, etc. inside the `@-webkit-keyframes` match those outside?
