### ISSUE TITLE
delay not working

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#2]
Hi @thomasjbradley!

Am struggling to put a delay on a h1 element.

I tried adding it in the format suggested by W3 schools, but it just seems to break the animation:

```
.h1-slide {
    -webkit-animation: right-in 1s linear 5s;
    animation: right-in 1s linear 5s;
}

@-webkit-keyframes right-in {
    0% {   
        transform: translateX(3000px);
        }

    80% {
        transform: translateX(-10px);
    }

    90% {
        transform: translateX(10px);
    }

    100% {
        transform: translateX(0px);
    }
}
```

I also tried using the long-hand version:

```
.h1-slide {
    -webkit-animation: right-in 10s linear;
    animation: right-in 10s linear;
    -webkit-animation-delay: 5s;
    animation-delay: 5s;
}

```

(I also tried it with the ease-in-out property instead of linear, which is what I prefer. Still no dice.)

But both of these just stop the animation entirely. Any ideas?

**Comment by thomasjbradley** [comment]
It looks okay.
Can you commit it so I can see the live version?

**Comment by vivkay** [comment]
Ok interesting, I have added two new animations to see how this is working (they are in two divs with paragraph type saying test slide 1, and test slide 2). 

Test slide 2 is doing something interesting...it appears instantly, then disappears off-screen to animate. I can't tell why it would be behaving like this. here's the code I have for them:

```
.test-slide1 {
    -webkit-animation: right-in 1s ease-in-out;
    animation: right-in 1s ease-in-out;
}

@-webkit-keyframes right-in {
    0% {   
        transform: translateX(3000px);
        }

    80% {
        transform: translateX(-20px);
    }

    90% {
        transform: translateX(40px);
    }

    100% {
        transform: translateX(0px);
    }
}

.test-slide2 {
    -webkit-animation: right-in 1s linear;
    animation: right-in 2s linear;
    -webkit-animation-delay: 1s;
    -animation-delay: 1s;
}

```

**Comment by vivkay** [comment]
(just committed with this @thomasjbradley )

**Comment by thomasjbradley** [comment]
It needs some default CSS so that it's starts off screen. Right now it gets rendered on screen, because there's no CSS associated with it, then the animation starts, which starts it off the screen and animates it in.

**Comment by vivkay** [comment]
Isn't that what this is telling it to do already though? (at 0% animated from 3000px to the right)?

```

@-webkit-keyframes right-in {
    0% {   
        transform: translateX(3000px);
        }

    80% {
        transform: translateX(-20px);
    }

    90% {
        transform: translateX(40px);
    }

    100% {
        transform: translateX(0px);
    }
}


.test-slide2 {
    -webkit-animation: right-in 1s linear;
    animation: right-in 2s linear;
    -webkit-animation-delay: 1s;
    -animation-delay: 1s;
}
```

**Comment by thomasjbradley** [comment]
The animation is only telling it to start at 3000px, but the browser is rendering it at its default location before starting the animation.

**Comment by vivkay** [comment]
ooo erm...how do I make it not do that? :P would I have to set it to display none at a certain time?

**Comment by thomasjbradley** [comment]
`.test-slide2` needs to be styled off screen, so that its default position is where it should start, like:

``` css
.test-slide2 {
  transform: translateX(3000px);
}
```

**Comment by vivkay** [comment]
This works! Except now after the animation is finished, the text disappears (see the latest commit for the 'test slide 2')

**Comment by thomasjbradley** [comment]
Add `forwards` into the `animation` property to make it stay where it ended.

**Comment by vivkay** [comment]
Thanks! It worked!
