### ISSUE TITLE
experimental: offset stroke with type

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#3]
Hi Thomas!

I really want to try to make my type look like what they have here, with the fill color and an offset stroke: http://www.shopify.ca/2014

I've spent about an hour trying to make this work but am just not succeeding! Here's what I've tried:

In my css, I tried adding a separate stroke and fill using the webkit stroke property (as this guy says to do: http://css-tricks.com/adding-stroke-to-web-text/). I managed to get the stroke to work, but couldn't figure out how to make it offset.

SO, then I tried to add two levels of the same type, one with a stroke and one with a fill. I positioned one absolute and the other relative, but they line up wonky and I am wary of putting pixel coordinates because it will be far more challenging to make it look good at different screen sizes.

Here's a bit of my code attempt:

HTML:

```
        <div class="unit unit-xs-1 unit-s-1-2 unit-m-2-3 unit-l-2-3 island">
            <h5 class="intro cursive title-slide center">An introduction to the wonderful world of</h5>
            <h1 class="giant center jiggle fill">HTML</h1>
            <h1 class="giant center jiggle stroke">HTML</h1>
        </div>
```

CSS:

```
.fill {
    color: white;
    position: relative;
}

.stroke {
    position: absolute;
    color: transparent;
    -webkit-text-stroke: 5px #E9625A;
    -webkit-stroke-offset: 10px;
}
```

Thanks @thomasjbradley!

**Comment by vivkay** [comment]
I also noticed that shopify managed to do this with textured type. Because I like a challenge, I'm going to try and work on some texture in the meantime, and am hoping I can have an offset stroke on top of textured type. Here's the tutorial I'm using for the texture: http://www.creativebloq.com/texturise-web-type-css-5124273  

...but I just noticed that this tutorial requires some javascript. Is there another way?

**Comment by vivkay** [comment]
(But also, do I need to create a backup text for browsers that may not support textured or outlined type?...how do we make this alternate type visible only when the other ones fail?)

**Comment by thomasjbradley** [comment]
For the alignment, they both need to be `absolute` and both inside something that is `relative`—relative is always for the wrapping element, absolute for the things you want to position.

It might be better to have the filled one being nothing (aka no `position`), and the stroke being absolute. But still the surrounding element would have to be relative.

**Comment by thomasjbradley** [comment]
For the texture, that tutorial is good, but don't do Step 4.
What you're primarily interested in is the CSS `mask-image` property.

**Comment by vivkay** [comment]
awesome beans-will try this!

**Comment by vivkay** [comment]
So I've decided I just want the white fill color and the coral/orange stroke offset. I've managed to get that, but at the cost of my grid it seems!

Heres's what funkiness is happening now:

![screen shot 2015-01-31 at 2 54 12 pm](https://cloud.githubusercontent.com/assets/6340292/5989529/27b30ffa-a959-11e4-9e9c-5e0b883513c7.png)

![screen shot 2015-01-31 at 2 54 27 pm](https://cloud.githubusercontent.com/assets/6340292/5989531/29dfdf74-a959-11e4-88ea-0f4cd407e80a.png)

And this is the code:

HTML

```
        <div class="unit unit-xs-1 unit-s-1-2 unit-m-2-3 unit-l-2-3 island">
            <h5 class="intro cursive title-slide center">An introduction to the wonderful world of</h5>
            <div class="title">
                <h1 class="giant center jiggle fill">HTML</h1>
                <h1 class="giant center jiggle stroke">HTML</h1>
            </div>
        </div>
```

CSS

```

.title {
    position: relative;
}

.fill {
    color: white;
    position: absolute;
}

.stroke {
    position: absolute;
    height: 120px;
    width: 100px;
    top: 60%;
    right: 75%;
    color: transparent;
    -webkit-text-stroke: 4px #E9625A;
}
```

CSS (animation)

```
.jiggle {
    -webkit-animation: jiggle 2s ease-in-out;
    animation: jiggle 2s ease-in-out;
}

@-webkit-keyframes jiggle {
    20% {
        opacity: 0;
        transform: rotate3d(0, 0, 1, 15deg);
    }

    40% {
        transform: rotate3d(0, 0, 1, -10deg);
    }  

    60% {
        transform: rotate3d(0, 0, 1, 5deg);
    }  

    80% {
        transform: rotate3d(0, 0, 1, -5deg);
    }  

    100% {
        opacity: 100;
        transform: rotate3d(0, 0, 1, 0deg);
    }  
}
```

Any thoughts @thomasjbradley 

I mean, I could just make it simple and solid and forget about all this jazz... but that would be boring! :P

**Comment by vivkay** [comment]
Do I need to mess with media queries to resize my type? 

(I also have this on the type that says 'HTML;)

CSS

```

.giant {
    font-size: 8rem;
    line-height: .6;
}
```

**Comment by thomasjbradley** [comment]
The font size being too big was my initial gut reaction. Try adding a background colour to the `h1` and see how wide it is—I feel like the text is just breaking out of it.

**Comment by vivkay** [comment]
this is what it looks like when I add a (garish but easy-to-see) red background. The text looks contained in it?

![screen shot 2015-01-31 at 3 41 30 pm](https://cloud.githubusercontent.com/assets/6340292/5989758/d3ac3be6-a95f-11e4-88ac-0e889ce4b727.png)

![screen shot 2015-01-31 at 3 41 24 pm](https://cloud.githubusercontent.com/assets/6340292/5989759/d5582ef0-a95f-11e4-86e1-fc467124876d.png)

**Comment by vivkay** [comment]
And this is what bothers me... when I take off the absolute position, the header works better (i.e. it wraps properly).

![screen shot 2015-01-31 at 3 45 38 pm](https://cloud.githubusercontent.com/assets/6340292/5989768/4173c7de-a960-11e4-8042-d4486ccd8c83.png)

**Comment by thomasjbradley** [comment]
The filled one doesn't likely need `position: absolute` but the stroke definitely does.

And in the last image you linked, directly above this comment, both of the text pieces are completely breaking out of their red boxes, especially the stroked one.

**Comment by vivkay** [comment]
Wow. I definitely was losing it yesterday HAH! You're totally right, the text is breaking out of the box. Is this because of the rem sizing?

Also, is there a way that I can get these two text 'boxes' to align automatically and still be responsive?

I want the HTML part to be giant, and the text on top to be smaller, but to line up on the edges. This is a screenshot of what I don't like to see (which is what I have now):

![screen shot 2015-02-01 at 12 38 06 pm](https://cloud.githubusercontent.com/assets/6340292/5993009/5c219822-aa0f-11e4-9ba5-4ea70cd66130.png)

**Comment by thomasjbradley** [comment]
I believe the breaking out is because of the width on the `h1` element.

What do you mean "align automatically"? (The answer is probably not.)

Lining up the edges: um, yeah, have fun with that one. If you don't mind the intro text wrapping then put it all in the same box and let the width be determined by the `h1`.

**Comment by vivkay** [comment]
Okie dokie! This clarifies things. Will try a different technique for the headlines then. Responsiveness is king. THANKS THOMASSSSS!!
