### ISSUE TITLE
bunny emergency!

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#4]
Hi @thomasjbradley

I just spent an age creating this beautiful bunny in illustrator. It's in pieces as png files, and compressed via image optim.

![screen shot 2015-01-31 at 2 34 08 pm](https://cloud.githubusercontent.com/assets/6340292/5989438/3d8da630-a956-11e4-94c8-6edc1aaa58fd.png)

But it's doing all kinds of weird things like not displaying and not being responsive... here's the code I have currently:

HTML

```
    <header role="banner" class="beige grid grid-middle island">
        <div class="unit unit-xs-1 unit-s-1-2 unit-m-1-3 unit-l-1-3 island bunny-parent">
            <div class="hat"></div>
            <div class="head"></div>
        </div>
     </header>
```

CSS

```
.bunny-parent {
    position: relative;
}

.hat {
    background-image: url(../img/hat.png);
    position: absolute;
    top: -100px;
    left: 100px;
    width: 100%;
    height: 100%;
    background-repeat: no-repeat;
}

.head {
    background-image: url(../img/head.png);
    position: absolute;
    top: -100px;
    left: 100px;
    width: 100%;
    height: 100%;
    background-repeat: no-repeat;
}
```

And here's what I see (just the tip of his hat): 
![screen shot 2015-01-31 at 2 32 53 pm](https://cloud.githubusercontent.com/assets/6340292/5989431/1c26f2d0-a956-11e4-9165-4a3c26acfc00.png)

I tried taking the bunny-parent class off, but this just makes his head huge and floating in space uncontrollably (because of the absolute positioning).

Ideas on how to get him to come together?

**Comment by thomasjbradley** [comment]
It's probably the widths and heights in %, try setting them in something else like `em`.

**Comment by vivkay** [comment]
I'm so sad @thomasjbradley, my bunny isn't working at all!

Here's what it looks like with width 100em and height 100em:

![screen shot 2015-02-01 at 1 44 58 pm](https://cloud.githubusercontent.com/assets/6340292/5993274/cf15978a-aa18-11e4-9131-6164b8f73e9f.png)

And width 100%, height 100em it starts to cut off his face:
![screen shot 2015-02-01 at 1 45 17 pm](https://cloud.githubusercontent.com/assets/6340292/5993275/d77c4c0c-aa18-11e4-9ff6-c80fd14f14f3.png)

I think I might give up on this bunny, and just upload one image at 200px by 100px and make it bounce up and down instead. I wanted to make his head and arms and ears move, but the positioning and lack of responsiveness here is causing me grief! What do you think?

Thanks!

**Comment by thomasjbradley** [comment]
That makes sense. Because you're using a `background-image`, you need to add `background-size` to scale the image inside its element.

**Comment by vivkay** [comment]
Aha! That does make-the-sense! thank you!
