### ISSUE TITLE
boo! An alignment problem!

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#5]
Hi again @thomasjbradley!

Soooo I like this button that I have happening, and it's positioning is great EXCEPT the little guy won't go centered. He's just stuck on the left-hand-side!

He's on his own grid-level row, he's got unit display of 1 at all screen sizes, he has text-align center, he has margins at ' 0, auto', he has display block... is one of these messing it up, or if not what am I doing wrong?

CSS

```
.button-mint {
    display: block;
    margin: 0, auto;
    position: absolute;
    border: 10px solid #fff;
    border-radius: 100px;
    height: 120px;
    font-size: 1.25rem;
    font-family: "raleway", sans-serif;
    padding: 20px;
    text-decoration: none; 
    text-align: center;
    line-height: 1.5rem;
    color: #fff;
    background-color: #89CDC2; 
    float: center;
}

.button-mint:hover {
    cursor: pointer;
    border: 10px solid #fff; 
    background-color: #282C4E;
}
```

HTML

```
            <div class="grid grid-middle">
                <div class="unit unit-xs-1 unit-s-1 unit-m-1 unit-l-1 island">
                    <div>
                        <p class="button-mint center">Learn<br><span class="bold">HTML!</span></p>
                    </div>
                </div>
```

THANK YOU!!!

**Comment by thomasjbradley** [comment]
There's quite a few different things happening all compounding to cause the problem:
1. That `.grid` is actually inside another grid so it's shrinking really narrow.
2. It has `position: absolute`
3. It has `float`
4. There's a comma between the 0 and auto in the margin
