### ISSUE TITLE
positioning problemos

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#6]
Hi @thomasjbradley, 

My bunny's parent element (set to position: relative) isn't working.

Here's what happens at a smaller screen size (things start overlapping).

![screen shot 2015-02-01 at 5 31 47 pm](https://cloud.githubusercontent.com/assets/6340292/5994211/88596612-aa38-11e4-8b0d-8ed468f9cf76.png)

How can I keep the bunny in it's place so that this is a responsive site? Is my only option to change it's size as a media query?

Thanks Thomas!!

**Comment by thomasjbradley** [comment]
I think then that the text and the bunny would have to be in the same relative element so that they can be grouped together.

**Comment by vivkay** [comment]
Thomas! What am I doing wrong? I tried to make the bunny an image in the html instead, and this seemed to be working but it still fails to stack at the smaller screen sizes. :(

I noticed that Anna has something similar on her site, but her text and image doesn't stack at the smaller size? http://annamisak.github.io/dsn1676-term-project/

I only have four elements on my page really, and it's taken me all weekend to get them to not even work. Is this due at the start of class tomorrow, or will we have time to troubleshoot during?

Thanks so much for your help this weekend.

**Comment by vivkay** [comment]
Oo I see that we have until 8pm tomorrow on canvas. THANK YOU THOMAS. I feel like I'm close but asking you in person will probably be WAY easier than stressing over misbehaving bunnies from home. 

You're the best!

(also...my button isn't aligning properly... but I'll save that for tomorrow...unless you know off the top of your head how to make it's absolute position-ness relative to the bottom of my header element?) :D
