### ISSUE TITLE
positioning

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#7]
Hi @thomasjbradley, 

I changed my svg animation so it's pretty much what I want. My problem now though is I'm getting some funky positioning issues with the background and my back-to-top button. 

![screen shot 2015-04-05 at 10 55 10 am](https://cloud.githubusercontent.com/assets/6340292/6997241/91cf5fb4-db82-11e4-8031-a1fc08117fac.png)

I want the beige background behind the title 'add some style' and to end after the bunny. The back-to-top button should be on white, as it's own separate entity. 

Any ideas?

Thanks!

**Comment by thomasjbradley** [comment]
Because both bunnies are `position: absolute` they aren't taking up space and forcing the beige colour down.
