### ISSUE TITLE
favicon question

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#8]
Hi @thomasjbradley, 

Am wondering about the checkpoint for our website 'has all the favicons'
1. Is this good as a favicon?

![screen shot 2015-04-13 at 5 25 05 pm](https://cloud.githubusercontent.com/assets/6340292/7125822/2f97a212-e202-11e4-8c27-697d91083137.png)
1. Are there other places for favicons, or types of favicons? (I noticed the check point was plural...)

Thanks!

**Comment by thomasjbradley** [comment]
Yep that's good.

Here's the other ones:
https://github.com/algonquindesign/html-css/tree/gh-pages/image-formats#favicons

**Comment by vivkay** [comment]
Woah! You can animate them with javascript! that's neat!

Is this browser one sufficient for this project, or are you looking for multiple other incarnations (apple touch, windows 8?)

Fanks!!

**Comment by thomasjbradley** [comment]
The browser one is definitely sufficient for this project.

**Comment by vivkay** [comment]
Perfecto!
