### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-term-project#9]
@thomasjbradley

What does this mean?

"Content has semantically appropriate elements?"

Thanks!

V

**Comment by thomasjbradley** [comment]
HTML semantics. Like choosing the correct tags for the content.

**Comment by vivkay** [comment]
hmm–like elements such as divs, nav, img etc. appropriately?

**Comment by thomasjbradley** [comment]
Yeppers.

**Comment by vivkay** [comment]
Awesome!
